### PR TITLE
Add generic OFX and PresidentChoice MasterCard importer

### PR DESCRIPTION
**Pull request by exlum**
Many major banks (at least in Canada) support downloading statements in OFX format.
This PR will add OFX importer for Silverstrike.
Note: 
- In order to use OFX importer 'ofxparse' package needs to be installed.
`$ pip install ofxparse`
- Import page has only CSV import button. Because import procedure for OFX is very similar, I think that button can be renamed to something more generic.

### CODE REVIEW

**Comment by exlum** [comment]
Yeah, sure. 
For CSV importer:
[mc-test.csv.txt](https://github.com/agstrike/silverstrike/files/2777407/mc-test.csv.txt)
For OFX importer:
[test.qfx.txt](https://github.com/agstrike/silverstrike/files/2777413/test.qfx.txt)

**Comment by simhnna** [comment]
thank you for the files. I'll add a couple more changes and merge it in.

For the PC-mastercard is the "card used for transaction" always a different card that should be imported into different personal accounts?

I would need to rework the import mechanism if that was the case

**Comment by exlum** [comment]
There is only one PC MC account, but they allow to have multiple card linked to this account. Each card has unique number. That number is shown on the statement. 
I'm not sure if that can be imported as different accounts. For example when payment is made it appears only on one (primary) card, so the balance needs to be updated for all other cards.

**Comment by simhnna** [comment]
merged it in another branch. The next time please use a branch to submit your changes, as it's highly unlikely my master branch will be the same as yours...

**Pull request closed without merging**
