### PR TITLE
WIP: Rework recurrences

### LINKED ISSUE #67: Add weekly and biweekly options to recurring transactions
Weekly and biweekly are both pretty basic options for recurring transaction intervals. There are likely more recurrence options needed but these two are simple to add and fundamental.

### PR DESCRIPTION
**Pull request by simhnna**
Fixes #67

### CODE REVIEW

**Comment by simhnna** [comment]
@roanutil I guess you should be able to get the job done using this merge request.
I'll do a little more testing before I merge it

**Comment by roanutil** [comment]
For the recurrence options, I've played with switching to a recurrence_interval and recurrence_multiplier. Recurrence intervals would be Days, Weeks, Months, Quarters, and Years. Then the multiplier is just the number of the selected interval. That's trading some simplicity for flexibility. Not sure how that weighs out. But figured I'd mention it.

**Comment by simhnna** [comment]
That's actually what I'm doing in this merge request. :D

I used reused the recurrence field and added a skip field. While I like your naming better, I guess I would prefer the neutral value of the field to be zero and not one.

**Comment by roanutil** [comment]
Looked more closely and yes that is the same thing. Sorry about that. The skip terminology mixed me up. Not sure what you mean about the neutral value.

I like the extra functionality for handling recurrence dates that fall on weekends.

**Comment by simhnna** [comment]
yeah, I'm aware of that... I had a couple of commits locally.
About the skipping I realized I probably want a `base_date that beside the `next_date` that can be used for the basis of calculations. I'm not yet sure how to make sure that "weekend-changes" don't result in future occurrences to diverge from the actual date you intended...

I still want to think about it a little/try it on my installation before I actually commit to something

**Comment by roanutil** [comment]
Totally understand. I was thinking the same looking at it. You are right that it would probably make more sense to create the transaction based on weekend handling, last day of the month, etc. Then advance the recurring transaction date by its interval unmodified by weekends and such.

**Pull request merged**
